2023-12-06 12:01:26,333 INFO    MainThread:27084 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2023-12-06 12:01:26,333 INFO    MainThread:27084 [wandb_setup.py:_flush():76] Configure stats pid to 27084
2023-12-06 12:01:26,333 INFO    MainThread:27084 [wandb_setup.py:_flush():76] Loading settings from C:\Users\aman.sa\.config\wandb\settings
2023-12-06 12:01:26,333 INFO    MainThread:27084 [wandb_setup.py:_flush():76] Loading settings from c:\Users\aman.sa\Documents\code\PicfPos\Image classifier\wandb\settings
2023-12-06 12:01:26,333 INFO    MainThread:27084 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-06 12:01:26,333 INFO    MainThread:27084 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-06 12:01:26,333 INFO    MainThread:27084 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-06 12:01:26,334 INFO    MainThread:27084 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\aman.sa\Documents\code\PicfPos\Image classifier\wandb\run-20231206_120126-004b5x61\logs\debug.log
2023-12-06 12:01:26,334 INFO    MainThread:27084 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\aman.sa\Documents\code\PicfPos\Image classifier\wandb\run-20231206_120126-004b5x61\logs\debug-internal.log
2023-12-06 12:01:26,334 INFO    MainThread:27084 [wandb_init.py:init():564] calling init triggers
2023-12-06 12:01:26,334 INFO    MainThread:27084 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-12-06 12:01:26,334 INFO    MainThread:27084 [wandb_init.py:init():589] re-initializing run, found existing run on stack: hulte67d
2023-12-06 12:01:26,336 INFO    MainThread:27084 [wandb_run.py:_finish():1962] finishing run amnx/PicfPos/hulte67d
2023-12-06 12:01:26,337 ERROR   MainThread:27084 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2023-12-06 12:01:26,337 INFO    MainThread:27084 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-12-06 12:01:26,337 INFO    MainThread:27084 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2023-12-06 12:01:26,337 INFO    MainThread:27084 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2023-12-06 12:01:26,337 INFO    MainThread:27084 [wandb_run.py:_restore():2185] restore
2023-12-06 12:01:26,338 INFO    MainThread:27084 [wandb_run.py:_restore():2191] restore done
2023-12-06 12:01:31,415 INFO    MainThread:27084 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2023-12-06 12:01:31,415 INFO    MainThread:27084 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2023-12-06 12:01:31,419 INFO    MainThread:27084 [wandb_run.py:_footer_sync_info():3796] logging synced files
2023-12-06 12:01:32,192 INFO    MainThread:27084 [wandb_init.py:init():614] starting backend
2023-12-06 12:01:32,192 INFO    MainThread:27084 [wandb_init.py:init():618] setting up manager
2023-12-06 12:01:32,194 INFO    MainThread:27084 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2023-12-06 12:01:32,195 INFO    MainThread:27084 [wandb_init.py:init():624] backend started and connected
2023-12-06 12:01:32,198 INFO    MainThread:27084 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2023-12-06 12:01:32,198 INFO    MainThread:27084 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-12-06 12:01:32,198 INFO    MainThread:27084 [wandb_init.py:init():716] updated telemetry
2023-12-06 12:01:32,251 INFO    MainThread:27084 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-12-06 12:01:33,528 INFO    MainThread:27084 [wandb_run.py:_on_init():2254] communicating current version
2023-12-06 12:01:34,144 INFO    MainThread:27084 [wandb_run.py:_on_init():2263] got version response 
2023-12-06 12:01:34,144 INFO    MainThread:27084 [wandb_init.py:init():800] starting run threads in backend
2023-12-06 12:01:39,154 INFO    MainThread:27084 [wandb_run.py:_console_start():2233] atexit reg
2023-12-06 12:01:39,154 INFO    MainThread:27084 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2023-12-06 12:01:39,154 INFO    MainThread:27084 [wandb_run.py:_redirect():2153] Wrapping output streams.
2023-12-06 12:01:39,154 INFO    MainThread:27084 [wandb_run.py:_redirect():2178] Redirects installed.
2023-12-06 12:01:39,155 INFO    MainThread:27084 [wandb_init.py:init():841] run started, returning control to user process
2023-12-06 12:01:39,155 INFO    MainThread:27084 [wandb_watch.py:watch():51] Watching
2023-12-06 12:03:40,767 INFO    MainThread:27084 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2023-12-06 12:03:40,767 INFO    MainThread:27084 [wandb_setup.py:_flush():76] Configure stats pid to 27084
2023-12-06 12:03:40,767 INFO    MainThread:27084 [wandb_setup.py:_flush():76] Loading settings from C:\Users\aman.sa\.config\wandb\settings
2023-12-06 12:03:40,767 INFO    MainThread:27084 [wandb_setup.py:_flush():76] Loading settings from c:\Users\aman.sa\Documents\code\PicfPos\Image classifier\wandb\settings
2023-12-06 12:03:40,767 INFO    MainThread:27084 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-06 12:03:40,767 INFO    MainThread:27084 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-06 12:03:40,770 INFO    MainThread:27084 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-06 12:03:40,770 INFO    MainThread:27084 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\aman.sa\Documents\code\PicfPos\Image classifier\wandb\run-20231206_120340-rinu3u8l\logs\debug.log
2023-12-06 12:03:40,770 INFO    MainThread:27084 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\aman.sa\Documents\code\PicfPos\Image classifier\wandb\run-20231206_120340-rinu3u8l\logs\debug-internal.log
2023-12-06 12:03:40,770 INFO    MainThread:27084 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000210C3EE9E50>
2023-12-06 12:03:40,770 INFO    MainThread:27084 [wandb_init.py:init():564] calling init triggers
2023-12-06 12:03:40,770 INFO    MainThread:27084 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-12-06 12:03:40,770 INFO    MainThread:27084 [wandb_init.py:init():589] re-initializing run, found existing run on stack: 004b5x61
2023-12-06 12:03:40,772 INFO    MainThread:27084 [wandb_run.py:_finish():1962] finishing run amnx/PicfPos/004b5x61
2023-12-06 12:03:40,772 INFO    MainThread:27084 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2023-12-06 12:03:40,772 INFO    MainThread:27084 [wandb_run.py:_restore():2185] restore
2023-12-06 12:03:40,772 INFO    MainThread:27084 [wandb_run.py:_restore():2191] restore done
2023-12-06 12:03:45,666 INFO    MainThread:27084 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2023-12-06 12:03:45,666 INFO    MainThread:27084 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2023-12-06 12:03:45,670 INFO    MainThread:27084 [wandb_run.py:_footer_sync_info():3796] logging synced files
